import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase = createClient('https://agxmsdzwncdshghogmhm.supabase.co','sb_publishable_PaAeF3fymLMZ3ZQJkOZCWw_7barSa3K');
const $ = selector => document.querySelector(selector);
const signInButton=$('#google-signin'), dashboard=$('#player-dashboard'), authPanel=$('#auth-panel');
signInButton.addEventListener('click',async()=>{signInButton.disabled=true;signInButton.textContent='Connecting to Google...';const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}${location.pathname}`}});if(error){$('#auth-copy').textContent=error.message;signInButton.disabled=false;signInButton.innerHTML='<span class="google-mark">G</span> Continue with Google <span>&#8599;</span>';}});
$('#signout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload();});
$('#profile-form').addEventListener('submit',async event=>{event.preventDefault();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const username=$('#username').value.trim(),status=$('#profile-status');if(username&&!/^[A-Za-z0-9_]+$/.test(username)){status.textContent='Username can only contain letters, numbers, and underscores.';return;}status.textContent='Saving...';const{error}=await supabase.from('profiles').update({display_name:$('#display-name').value.trim(),username:username||null,bio:$('#bio').value.trim(),updated_at:new Date().toISOString()}).eq('id',user.id);status.textContent=error?error.message:'Profile saved.';if(!error)await loadProfile(user);});
async function loadProfile(user){const{data:profile}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(!profile)return;$('#player-name').textContent=profile.display_name||user.user_metadata?.full_name||'Player';$('#player-email').textContent=user.email||'';$('#player-rank').textContent=profile.rank_title;$('#player-points').textContent=Number(profile.total_points).toLocaleString();$('#player-avatar').src=profile.avatar_url||user.user_metadata?.avatar_url||'assets/bazoo-controller.png?v=2';$('#display-name').value=profile.display_name||'';$('#username').value=profile.username||'';$('#bio').value=profile.bio||'';const[{data:connections},{data:events}]=await Promise.all([supabase.from('social_connections').select('provider,username,connection_status,subscriber_status').eq('user_id',user.id),supabase.from('point_events').select('amount,description,event_type,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(8)]);if(connections?.length)$('#connection-list').innerHTML=connections.map(item=>`<div><b>${escapeHtml(item.provider)}</b><span>${escapeHtml(item.subscriber_status==='verified'?'Subscriber verified':item.connection_status)}</span></div>`).join('');if(events?.length)$('#points-list').innerHTML=events.map(item=>`<div><span>${escapeHtml(item.description||item.event_type)}</span><b>${item.amount>0?'+':''}${item.amount}</b></div>`).join('');}
async function loadLeaderboard(){const{data}=await supabase.from('leaderboard').select('*').order('position').limit(25);if(!data?.length)return;$('#leaderboard').innerHTML=`<div class="leaderboard-row leaderboard-labels"><span>Rank</span><span>Player</span><span>Title</span><span>Points</span></div>${data.map(p=>`<div class="leaderboard-row"><strong>#${p.position}</strong><span>${escapeHtml(p.display_name||p.username||'Bazoo Player')}</span><small>${escapeHtml(p.rank_title)}</small><b>${Number(p.total_points).toLocaleString()}</b></div>`).join('')}`;}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);}
const{data:{session}}=await supabase.auth.getSession();if(session?.user){authPanel.hidden=true;dashboard.hidden=false;await loadProfile(session.user);}await loadLeaderboard();

